# Generated by Django 4.2.3 on 2023-10-11 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_buytransaction_selltransaction_userwallet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buytransaction',
            old_name='symbol',
            new_name='share_symbol',
        ),
    ]
