# Generated by Django 4.2.3 on 2023-10-13 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_rename_symbol_buytransaction_share_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buytransaction',
            name='user_wallet',
        ),
    ]
